### ISSUE TITLE
Accepted formats include pdb, pdb.gz, and cif?

### ISSUE THREAD

**Issue by BinhongLiu** [awfderry/COLLAPSE#10]
Hi.
I tested the Embed entire dataset of PDB files script (https://github.com/awfderry/COLLAPSE#embed-entire-dataset-of-pdb-files) with some .cif structures, but it seemed to be that the .cif format was not accepted.

the log is here:
(COLLAPSE) [ac1daawz21@login03 COLLAPSE-main]$ python embed_pdb_dataset.py /work/home/ac1daawz21/test/S1/1/ /work/home/ac1daawz21/test/S1/ --filetype cif
Traceback (most recent call last):
  File "embed_pdb_dataset.py", line 23, in <module>
    dataset = load_dataset(args.data_dir, args.filetype, transform=transform)
  File "/work/home/ac1daawz21/miniconda3/envs/COLLAPSE/lib/python3.8/site-packages/atom3d/datasets/datasets.py", line 441, in load_dataset
    raise RuntimeError(f'Unrecognized filetype {filetype}.')
RuntimeError: Unrecognized filetype cif.

**Comment by awfderry** [comment]
Sorry for the inconvenience, this appears to be due to the underlying ATOM3D function. There are two options to fix this for now: (1) pull the latest version of ATOM3D from [here](https://github.com/drorlab/atom3d), or (2) convert your dataset to PDB format.

**Comment by BinhongLiu** [comment]
Yes! The latest version of ATOM3D supported the .cif format. Thanks!
